project:
  type: default
  output-dir: docs
  render:
    - relatorio_ipca.qmd

lang: pt

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    toc-title: "Sumário"
    toc-location: left
    number-sections: true
    code-fold: false
    code-tools: false
    fig-width: 9
    fig-height: 5
    fig-dpi: 150
    fig-align: center
    embed-resources: true
    smooth-scroll: true

execute:
  freeze: auto
  echo: false
  warning: false
  message: false
  cache: false
